In [15]:
import numpy as np
print('hi')

x = np.array([[1,2,3],[1,2,3]])
print(x)

print(x.ndim)

hi
[[1 2 3]
 [1 2 3]]
2


In [5]:
x = [1,2,3,4]
y = np.array(x)

print(x,y)

[1, 2, 3, 4] [1 2 3 4]


In [11]:
arr = []
for i in range(1,6):
    j = str(i)
    num = input("Enter number " + j + ": ")
    try:
        num = int(num)
        arr.append(num)
    except:
        print("not a numeric value")
print(arr)

Enter number 1:  21
Enter number 2:  12
Enter number 3:  e


not a numeric value


Enter number 4:  21
Enter number 5:  4


[21, 12, 21, 4]


In [13]:
x = np.array([[1,2,3],[1,2]])
print(x)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [18]:
x = np.array([[1+2,'s'],[2.3,'d']])
print(x)

[['3' 's']
 ['2.3' 'd']]


In [29]:
x = np.ones((5,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [26]:
ar_dia = np.eye(5,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
x = np.array([[1,2,[2,2]],[2,3,[5,6]]])
print(x)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.

In [30]:
rn_ar = np.random.uniform(2,7,(3,5))
print(rn_ar)

[[4.59750302 6.70362935 2.35968876 5.85638347 4.61013399]
 [6.87154254 4.8712187  3.68074684 4.66055733 4.48379849]
 [2.9885888  3.90499164 5.99533325 2.1284103  3.27308573]]


In [31]:
rn_ar = np.random.randint(2,7,(3,5))
print(rn_ar)

[[3 2 5 6 5]
 [6 6 4 4 6]
 [2 5 2 6 6]]


In [33]:
x = np.array([1,2])
print(x.dtype)

int64


In [34]:
ar1 = np.array([1,2,3])
ar2 = np.array([3,2,1])

rslt1 = ar1 + ar2
rslt2 = np.add(ar1,ar2)

print(rslt1)
print(rslt2)

[4 4 4]
[4 4 4]


In [35]:
ar1 = np.array([[1,2,3],[1,2,2]])
ar2 = np.array([[2,5,7],[5,2,7]])

rslt = ar1 * ar2

print(rslt)

[[ 2 10 21]
 [ 5  4 14]]


In [40]:
ar1 = np.array([[[21,22],[12,12]],[[12,2],[24,5]]])
print(np.min(ar1,axis=0))

[[12  2]
 [12  5]]


In [63]:
import math
arr = np.array([1,4,3,2,6,7,1,2,3,1,2,3,3,2,3,2,2,4,6,7,8,4,3,2,4])

lnth = arr.size
print(lnth)
sqr_lnth = np.sqrt(lnth)

rows = math.ceil(sqr_lnth)
colums = math.floor(sqr_lnth)

r_ar = arr.reshape(rows,colums)

print(r_ar)


25
[[1 4 3 2 6]
 [7 1 2 3 1]
 [2 3 3 2 3]
 [2 2 4 6 7]
 [8 4 3 2 4]]
